[package]
name = "track2line_gui"
version = "0.2.1"
edition = "2024"

[dependencies]
egui="0.31.*"
eframe = "0.31.1"
egui-file-dialog = "0.9.0"
track2line_lib = {git = "https://github.com/Uliboooo/track2line_lib", tag = "0.3.0"}